### PR TITLE
add minus signs to some notations and support negative numbers

### LINKED ISSUE #5: Inputting a negative number hangs the demo page.
Inputting a negative number into the input box on the demo page results in a freeze. (I think this might be related to prime notation?)

### PR DESCRIPTION
**Pull request by dan-simon**
The demo page no longer freezes for negative numbers; Roman and Dots still say undefined on negative inputs, but adding a negative sign to either of those seemed a bit weird in a way that adding it to prime, Zalgo, and Shi didn't.
Fixes #5

### CODE REVIEW

**Comment by dan-simon** [comment]
That second commit was a first stab at #6; it's not complete, but at least ??? is shown rather than the page freezing. For a real attempt at #6, I think some either some looser parsing mechanism than Decimal.fromString or a looser for Decimal.fromString is needed, probably preferably the latter (I'd do a PR for that). Also, I would catch just DecimalErrors (which occur when you enter alphabetic gibberish) if I knew how, but the only way I saw to do that was string matching.

**Comment by dan-simon** [comment]
I added a looser parsing mechanism as mentioned above. As a side benefit, there's no longer a `catch (e)` in the code.

**Comment by razenpok** [comment]
Thanks! Add me to reviewers when you are done fiddling with code.

**Comment by razenpok** [comment]
As a side note: put "fixes #X" in PR description, not in title

**Comment by dan-simon** [comment]
I think it's ready. Some notations still work badly with negative numbers but at least they don't freeze, and in most of the remaining cases I think the best fix is more complicated than adding a minus sign. (Indeed, even with Zalgo, I'm now wondering if the minus sign should also be zalgo-ized. That's probably up to Spectral, though.)

**Comment by dan-simon** [comment]
Also, it seems like pull request authors can't request reviews unless they are either a repository owner or collaborator with write access to the repository, so consider yourself added as a reviewer (and probably add yourself as a reviewer).

**Review by razenpok — APPROVED** [review]

**Pull request merged**
