### PR TITLE
prime notation fix

### LINKED ISSUE #10: prime notation is wrong
https://github.com/antimatter-dimensions/notations/blob/ca22e028f62fb5616d13b0bc920e9d52106724de/src/prime.ts#L59-L63

First, this is wrong- it will produce "factorizations" that are not equal to the original number. Second, 10k is ridiculously low! You hardly ever see numbers that low in antimatter dimension.

I realize that this is intended to be a shorthand, so 10007 is written "(2²×5²)^(2)" in prime notation for the same reason that it is written "1.00e4" in scientific. I also realize that integer factorization is in NP and that you have to cut corners at some point in favor of gameplay.

However, incorrect factorizations that doesn't even share any factors with the original number is borderline offensive! Can we do better?

### PR DESCRIPTION
**Pull request by dan-simon**
Fixes #10 (I hope). See that issue for more info.

Apparently this version of prime notation can factor about 4000 numbers per second on Safari, 5 times that on Chrome. Superscripts 10 and above display oddly but I think they also did that before. I changed some design decisions about parentheses in an attempt to use as few as possible while remaining unambiguous (which I'm not completely certain I did correctly). @Ikerstreamer could you please also review this (in addition to Razen)?

### CODE REVIEW

**Comment by dan-simon** [comment]
Just making it clear that this should be merge-able if performance isn't an issue (and the other PR should be merge-able too).

**Comment by razenpok** [comment]
Sorry, recovering from massive burnout - will check this weekend

**Comment by dan-simon** [comment]
That's fine, take as long as you want. If it's inconvenient or worse to review it this weekend, then don't.

**Comment by dan-simon** [comment]
Added in #44 as a new community notation (Precise Prime).

**Pull request closed without merging**
