### PR TITLE
Update break_infinity.js imports

### PR DESCRIPTION
**Pull request by EdricChan03**
To include fix from PR Patashu/break_infinity.js#67 and issue Patashu/break_infinity.js#66

(Sidenote: I would strongly recommend that the `dist` folder be **not** committed to the main GitHub repository such that it's easier to maintain)

### CODE REVIEW

**Review by razenpok — COMMENTED** [review]
Fix conflicts and we should be gtg

**Comment by EdricChan03** [comment]
I've rebased the PR as requested

(EDIT: I've just noticed that there are minified versions of the JS files in the `docs` folder - is this intentional?)

**Comment by razenpok** [comment]
We can replace the `docs` version with CDN links, but then how would you test docs locally?

**Comment by EdricChan03** [comment]
Oh I just realised what the `build:*` NPM scripts do - you can ignore my comment

**Review by razenpok — APPROVED** [review]

**Pull request merged**
