### PR TITLE
Fours notation

### PR DESCRIPTION
**Pull request by Buck4437**

### CODE REVIEW

**Comment by dan-simon** [comment]
Are numbers between 1 and 0.5 (like 0.9) supposed to be 4÷4÷(4÷4)? Seems pretty redundant.

**Comment by dan-simon** [comment]
(there are also cases of multiplication and division by 4, as in ~~24~~ 96 for some reason, but ehh those are harder to get rid of)

**Comment by Buck4437** [comment]
I've changed the display between 0.5 and 1 (and most of the fractions), but I don't really know how to fix the display of other numbers like 96 without some ugly code so those will have to stay that way.

**Comment by dan-simon** [comment]
Sorry for commenting on this after merging it but I was thinking about it and I just noticed that 7 can be written `(4!+4)/4` for a saving of one 4, and similarly 12 can be written `4!/√4` for a saving of two 4s. I wonder if these changes (and maybe other small-number changes if I think of any) should be made or not, and since you made the notation I'd like your opinion.

**Comment by Buck4437** [comment]
You are more than welcomed to do so! I have also noticed that 10 can be expressed as `4!÷4+4`, saving a 4 in the process. It would be great if you can also include this change.

**Comment by dan-simon** [comment]
I made those three changes (remembering to use ÷ rather than / for the two I mentioned). Let me know if you think of any more ways to reduce 4 usage in the 1-16 part.

**Pull request merged**
