### PR TITLE
added 2 new notations: greek letters and Omega

### PR DESCRIPTION
**Pull request by ghost**
if there are any errors or doubts with the .ts files, please tell me.

### CODE REVIEW

**Comment by dan-simon** [comment]
Several things:

* `class OmegaNotation extends Notation` needs to be `export class OmegaNotation extends Notation` so that other files can access OmegaNotation.

*
```
export * from "./greekletters";
export * from "./omega";
```
needs to be added to the end of src/index.js so that ADNotations has GreekLettersNotation and OmegaNotation as properties, and
```
    N.GreekLettersNotation,
    N.OmegaNotation
```
needs to be added to the end of the list of notations in docs/index.js (the list starting with `notations = `) so that the HTML demo has all the notations.

* The compiling-to-JS step is important for testing. For me running `npm install` in the terminal initially and `npm run build; cp dist/ad-notations.min.js docs/ad-notations.min.js` in the terminal every time I change something seems to work for compiling to JS.

* I'm somewhat worried by how OmegaNotation doesn't distinguish, for example, 8 from 15. I'm also worried about how it represents both 8e23 and 2e26 as ω(ψ)^β, but represents, for example, 1e25 as ω(ψ)^Σ, even though 1e25 is in the range between 8e23 and 2e26. I think this (a < b < c, but format(a) = format(c) != format(b)) is a property we're trying to avoid.

* NG+++ has a Greek notation that this is different from (not in this library, though). I think GreekLetters and Greek are different enough names that the notations being different is reasonable, but I'm not sure.

**Comment by ghost** [comment]
I export those classes now, but running npm run made ADNotations undefined.

**Comment by dan-simon** [comment]
I think ADNotations was undefined due to some weird Windows/Mac encoding issue, I'm trying to figure out what the issue is exactly.

**Comment by dan-simon** [comment]
OK, I figured it out to some extent. The issue is that somehow an extra character (\u001a, control-z) got added to the end of docs/ad-notations.min.js. I would suggest deleting that character when you want to test. Also, remember to add
```
    N.GreekLettersNotation,
    N.OmegaNotation
```
to the end of the list of notations in docs/index.js.

**Comment by ghost** [comment]
ok, i'll do it later

**Comment by ghost** [comment]
I revised the Omega notation and added the 2 notations to the docs/index.html page

**Comment by dan-simon** [comment]
After any change to a notation file (such as changing Omega Notation), it's necessary to run `npm run build; cp dist/ad-notations.min.js docs/ad-notations.min.js` again (and delete the extra \u001a character at the end of docs/ad-notations.min.js if it shows up again). I assume you did this but am just making sure.

Also, I can't find your most recent commit. If both notations are working on the docs/index.html page then I think you should push the commit to your cook1ee-notations branch if you haven't pushed it already.

**Comment by ghost** [comment]
weird, I commited over github desktop and it is shown there, but on on web. What should I do?

**Comment by ghost** [comment]
Done, it worked when I commit+pushed with tortoisegit. As I said, I revised the omega notation (to have less significant changes in the number noticed) and added them to docs/index.html (everything should work now).

**Comment by dan-simon** [comment]
It seems to be working to me, and to have enough precision. I'm not sure if there are cases where a < b < c but format(a) = format(c) != format(b), but if so they're high enough that I don't think it matters (it's like how in Scientific 1e1e5 and 1e1.0001e5 are formatted the same, but 1.01e1e5 isn't).

**Comment by ghost** [comment]
Since the scale is assumed linearily now, format(a) = format(c) != format(b) should happen never to very rarely and easily distinguishable.
If there are any concerns left, please tell me :) I can try to look into them. Otherwise, I'd find it awesome if the notations get added to the library, but I don't want to pressure.

**Comment by dan-simon** [comment]
Razenpok is the only one who can actually merge as far as I know, and he'll probably want to look at this and make some code style recommendations first. But I at least have no concerns left :)

**Comment by ghost** [comment]
@Razenpok sorry, but I'd like to know if you can take a look at those 2 notations if you have the time.

**Comment by razenpok** [comment]
Rather busy taking a look myself as of right now. I'll ping AD dev team to see if they have some time for it.

**Comment by dan-simon** [comment]
Added in #44 as three community notations.

**Pull request closed without merging**
